version: 2

sources:
  - name: jaffle_shop
    database: til_portfolio_projects 
    schema: jaffle_shop  
    tables:
      - name: orders
        description: >
          One record per order. Includes cancelled and deleted orders.
        columns:
            - name: id
              description: Primary key of the orders table
              tests:
                - unique
                - not_null
            - name: status
              description: Note thatthe status can change over time

      - name: customers

  - name: stripe
    database: til_portfolio_projects
    schema: stripe
    tables:
      - name: payment